export enum MenuItemList {
    Dashboard,
    Student,
    Skill,
    SocietyMember,
    Company,
    Feedback,
    UploadCV,
    GenerateSchedule,
    Schedule,
    InterviewedAndShortListedStudents,
    GiveEventFeedback,
    DisplayEventFeedback,
    StudentFeedback,
    EventSummary,
};
